<?php

namespace App\Http\Resources\RefundRequest;

use Illuminate\Http\Resources\Json\JsonResource;

class RefundRequestResource extends JsonResource
{

    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }

}
